export const GET_FACILITIES = 'GET_FACILITIES';
export const ADD_FACILITIES = 'ADD_FACILITIES';
export const DELETE_FACILITIES = 'DELETE_FACILITIES';
export const UPDATE_FACILITIES = 'UPDATE_FACILITIES'
export const LOADING_FACILITIES = 'LOADING_FACILITIES'  

export const GET_ORGANIC = 'GET_ORGANIC';
export const ADD_ORGANIC = 'ADD_ORGANIC';
export const EDIT_ORGANIC = 'EDIT_ORGANIC';
export const DELETE_ORGANIC = 'DELETE_ORGANIC';



